### ISSUE TITLE
HTTP 500 Error when generating excel with multiple sheets

### ISSUE THREAD

**Issue by MathEman-1** [straydogstudio/axlsx_rails#103]
Hey Guys,

for weeks now we are running into the issue, that at a certain threshold of exported data, we get a HTTP 500 error, instead of the Excel Download window.

It only happens after a certain number of exported sheets (around 15 sheets with 2-3 a4 pages of content with some excel charts), however this also changes (no pattern detectable). We don't use any delayed jobs or job queue for that right now. It first came up when we tried to add some images to the export, which we gave up and reverted to export without any pictures (due to the same issue).

If there is something wrong with the data, we can find some evidence in our logs, with the HTTP 500 error, we just get nothing.

Any ideas why this might be happening or what we could try?

Some details about our setup:
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails'
2 AWS frontend servers with a Load Balancer in front
AWS RDS with MySQL

**Comment by straydogstudio** [comment]
Have you tried duplicating the error with pure ruby (e.g. in a script) so the Rails request mechanism (and therefore axlsx_rails) is left out of it?  [See the script docs](https://github.com/straydogstudio/axlsx_rails#scripts). You may be running into an Axlsx bug. Also, you could try the Axlsx github repo instead of '2.1.0.pre'.

**Comment by MathEman-1** [comment]
Thanks for the suggestion! We haven't tried that, but will give it a go.

I will close this issue for now and add one later if we find out some more details - right now there is not much to discuss.

**Comment by straydogstudio** [comment]
It doesn't sound like you have much data, but one shortcoming of Axlsx is it loads everything into memory before it writes to disk. FYI.
