### ISSUE TITLE
deprecated function

### ISSUE THREAD

**Issue by dribeiroexpertise** [straydogstudio/axlsx_rails#109]
after trying the `basic` example I`ve got this warning message 

.rvm/gems/ruby-2.5.1/gems/axlsx-2.1.0.pre/lib/axlsx/util/simple_typed_list.rb:150: warning: constant ::Fixnum is deprecated
-----------------------------------------------
require 'axlsx'
puts "initial vars"
p = Axlsx::Package.new
wb = p.workbook
puts "generate spreadsheet"
  wb.add_worksheet(:name => "Basic Worksheet") do |sheet|
    sheet.add_row ["First Column", "Second", "Third"] #<-----the warning happen HERE
    sheet.add_row [1, 2, 3]
    sheet.add_row ['     preserving whitespace']
  end
  
puts "end"

**Comment by straydogstudio** [comment]
Looks like an Axlsx issue. I suggest posting it there.
