### ISSUE TITLE
Compatibility with Rails 6: Single arity template handlers are deprecated.

### ISSUE THREAD

**Issue by ashleyHutton** [straydogstudio/axlsx_rails#112]
Rails 6 update is causing this deprecation warning:

```
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> ActionView::Template::Handlers::AxlsxBuilder#call(template)
To:
  >> ActionView::Template::Handlers::AxlsxBuilder#call(template, source)
 (called from <main> at /app/config/environment.rb:5)
```

I'm guessing the fix is in [template_handler.rb](https://github.com/straydogstudio/axlsx_rails/blob/master/lib/axlsx_rails/template_handler.rb):
```
def call(template)
 ...
end
```
should be
```
def call(template, source)
 ...
end
```

**Comment by straydogstudio** [comment]
Thanks @ashleyHutton . I've not looked at Rails 6 yet. Was there a documentation url with the error?

**Comment by ashleyHutton** [comment]
@straydogstudio no, but it looks like this deprecation warning was introduced in [28f88e0](https://github.com/rails/rails/commit/28f88e0074f473f58c2d3fd54cb3daff81027c12) as part of [#35119](https://github.com/rails/rails/pull/35119).

**Comment by teohm** [comment]
@straydogstudio Since Rails 6.0 has been released, by any chance we can release a new version for this gem?

**Comment by straydogstudio** [comment]
I'll see what I can do. I'm probably going to fork axlsx into a community organization and move axlsx_rails into it. axlsx_rails needs a release of axlsx to fix several issues.

**Comment by straydogstudio** [comment]
@teohm New version released. 0.6.0. Matches with the new 3.0.0 caxlsx gem.
