### ISSUE TITLE
undefined method `reopen' for "streamed":String Did you mean?  prepend

### ISSUE THREAD

**Issue by Kuassari** [straydogstudio/axlsx_rails#116]
I already saw the issue https://github.com/straydogstudio/axlsx_rails/issues/18 and it didn't help at all
As the title said I get this message when try to export to export.xlsx

ruby version: 2.5.3
rails version: 4.2.11

gemfile:
```
gem 'rails', '4.2.11'
gem 'write_xlsx'
gem 'axlsx'
gem 'axlsx_rails'
gem 'rubyzip'
```

bundle install:
Using rubyzip 1.2.2
Using axlsx 1.3.6
Using axlsx_rails 0.1.5

export.xlsx.axlsx:
```
wb = xlsx_package.workbook
wb.add_worksheet(name: "#{@organization.name} Accounts") do |sheet|

  # Create headers
  sheet.add_row ["Account id", ""Member id", "Member name", "Member email"]

  # Create entries for each header
  @accounts_paginated.each do |account|
    account.members.each do |member|
      sheet.add_row [account.id, member.id, member.name, member.email]
    end
  end
end
```

**Comment by straydogstudio** [comment]
If you are indeed using axlsx_rails 0.1.5, that is quite old. You will want to get that to 0.5.2.
