### ISSUE TITLE
Add styles via function call

### ISSUE THREAD

**Issue by ilyakrasnov** [straydogstudio/axlsx_rails#30]
We have a big spreadsheet generator and want to clean up the code a bit. Here is a shortened example:

```
p.workbook.styles do |s|
  red_bold_light_yellow_all_borders           = sheet.add_style fg_color: "FF0000", b: true, bg_color: "FFFF99", border: {style: :thin, color: "000000"}
  bold_light_yellow_all_borders_right_aligned = sheet.add_style                     b: true, bg_color: "FFFF99", border: {style: :thin, color: "000000"}																				  , alignment: {horizontal: :right}

  p.workbook.add_worksheet(name: sheet_names(pool)[0]) do |sheet|
    sheet.add_row ["Intern", "Datum"], style: [red_bold_light_yellow_all_borders, bold_light_yellow_all_borders_right_aligned]
  end
end
```

The goal is to replace style generations with one function call like this:

```
p.workbook.styles do |s|
  generate_styles(s)

  p.workbook.add_worksheet(name: sheet_names(pool)[0]) do |sheet|
    sheet.add_row ["Intern", "Datum"], style: [red_bold_light_yellow_all_borders, bold_light_yellow_all_borders_right_aligned]
  end
end

def generate_styles(sheet)
  red_bold_light_yellow_all_borders           = sheet.add_style fg_color: "FF0000", b: true, bg_color: "FFFF99", border: {style: :thin, color: "000000"}
  bold_light_yellow_all_borders_right_aligned = sheet.add_style                     b: true, bg_color: "FFFF99", border: {style: :thin, color: "000000"}																				  
end
```
We get a syntax error on _generate_styles_  because of the special syntax of this gem (I suppose).

Do you have an idea how to solve it? Thanks in advance!

**Comment by straydogstudio** [comment]
@ilyakrasnov Off the top of my head, have you tried it as a helper? I'm not sure I like it in that spot, but let me know if it works. If not, I'll get back to it and figure it out.

Would you rather define it in template or out?

**Comment by sly7-7** [comment]
Confirm this works by defining and using helpers :smile:

**Comment by straydogstudio** [comment]
@sly7-7 Thanks for confirming this. Again this should be added to the docs.

**Comment by kashifnaseer** [comment]
When i use same code in my application, i get following error . am i missing something ?
       
       undefined local variable or method `red_bold_light_yellow_all_borders' 

 file  bids_helper.rb

       module BidsHelper
        def generate_styles2(sheet)
         red_bold_light_yellow_all_borders           = sheet.add_style fg_color: "FF0000", b: true, bg_color:    "FFFF99", border: {style: :thin, color: "000000"}
         bold_light_yellow_all_borders_right_aligned = sheet.add_style                     b: true, bg_color: "FFFF99", border: {style: :thin, color: "000000"}                                                                                  
        end
      end

      workbook = xlsx_package.workbook
      workbook.styles do |s|
      generate_styles2(s)

      workbook.add_worksheet(name: "sss") do |sheet|
        sheet.add_row ["Intern", "Datum"], style: [red_bold_light_yellow_all_borders,     bold_light_yellow_all_borders_right_aligned]
       end
    end

gem 'axlsx',                        github: 'randym/axlsx'
gem 'axlsx_rails',                  '>=0.4'

**Comment by sly7-7** [comment]
@kashifnaseer To use the helper, it has to be a function.
For example, in my use case, I have defined a StylesHelper module like this:

```ruby
module StylesHelper
  def sheet_title_style(workbook)
      workbook.styles.add_style fg_color: 'f4f4f4',
                                bg_color: '01afe7',
                                sz: 14,
                                alignment: { horizontal: :center, vertical: :center }
    end
end
```

and I use it like this, in a .axlsx file:

```
sheet.add_row [title], style: sheet_title_style(wb), :widths => [:ignore]
```

**Comment by kashifnaseer** [comment]
@sly7-7 thanks for your quick reply. I do have a function but now my concern is: 

    should there be a separate function for each style or all styles need to be in 1 function?

like in example above, there are 2 styles **red_bold_light_yellow_all_borders** and **bold_light_yellow_all_borders_right_aligned**  in the same action **generate_styles(sheet)** should it also work in this way ? 

If yes, how i can do it ?

**Comment by kashifnaseer** [comment]
Thanks for you quick reply @sly7-7. I'll create function for each style then
