### ISSUE TITLE
How to test the resulting workbook ?

### ISSUE THREAD

**Issue by sly7-7** [straydogstudio/axlsx_rails#31]
I just tried to make a move from using axlsx only to axlsx+axlsx_rails. This was great until I wanted to test.
Previously, I manually created the axlsx package and the workbook in a kind of helper, used in a controller, then I used to test this helper in isolation.
I could not find a way to access the resulting workbook in a ActionView::TestCase after I callled the render helper.
Maybe I just missed something, otherwise how would do this kind of things ? Let me now if I can help :smile:

**Comment by straydogstudio** [comment]
You can look at this test to see how I do at least something similar:
https://github.com/straydogstudio/axlsx_rails/blob/master/spec/axlsx_builder_spec.rb#L23-29

AB is just the Axlsx template handler. VT is a struct that mimics an ActionView::Template class, presenting a 'source' method to retrieve the content of the template. By instantiating xlsx_package outside the eval (line 24), and then calling eval, you have access to the generated spreadsheet after the eval (line 26.) Then you can test it.

If you are testing your helpers, you'll probably have to include them in your specific test so they are in the eval context ([that's really all ActionView does anyway](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers.rb#L39-L62).)

If that doesn't answer your question, post what code you are trying to test, and what you have for testing so far. If that *does* answer your question, let me know and close the issue.

For posterity, consider showing your problem and solution here. I'll eventually add it to the Readme. It should have a testing section. I'll give you credit of course.

**Comment by sly7-7** [comment]
Thanks to your example, was be able to make a test.
Considering this simplified template:
```ruby
@wb = xlsx_package.workbook
@wb.styles do |s|
  header_style = s.add_style fg_color: "f4f4f4"
  default_row_style = s.add_style alignment:  { vertical: :center}
  @wb.add_worksheet(name: "A worksheet") do | sheet |
    sheet.add_row ['A', 'B', 'C'], style: header_style
    dataRows = someHelper(@bar, @foo) # helper defined in a AxlsxHelper module
    dataRows.each do | dataRow |
      sheet.add_row dataRow
    end
  end
end
```

With this test:

```ruby
require 'spec_helper'
require 'axlsx_helper'

describe 'my_action' do
  include AxlsxHelper

  AB = ActionView::Template::Handlers::AxlsxBuilder
  VT = Struct.new(:source)

  let( :handler ) { AB.new }

  let( :template ) do
    VT.new(File.read(Rails.root.join('app', 'views', 'my_view', 'my_action.xlsx.axlsx')))
  end

  it "do what it should" do
    @foo = 'foo'
    @bar = 'bar'
    
    eval( AB.call template )
    
    expect(@wb.worksheets.length).to eq(1)
    sheet = @wb.worksheets[0]
    expect(sheet.name).to eq('A worksheet')
    expect(sheet).to have_header_cells ['A', 'B', 'C']
  end
end
```

So, that works. Now I wonder if it is possible to reduce the noise (AB, VT, eval). Also I'm not sure if having to declare all those instance variable is a good pattern. (@wb, @foo, @bar)
I'm don't know much about extending spec/rspec, but do you know if it would be possible to have some kind of AxlsxTestCase which could hide those noisy things ?

**Comment by sly7-7** [comment]
So, for posterity, I've refactored a bit, and was able to make (I think) the things more clear.
Firstly, I define a shared_context:

```ruby
require 'axlsx/shared_helper'

RSpec.shared_context "axlsx" do

  include Axlsx::SharedHelper

  # all xlsx specs describe must be normalized
  # "folder/view_name.xlsx.axlsx"
  # allow to infer the template path
  template_name = description

  let(:template_path) do
    ['app', 'views', template_name]
  end

  def render_template(locals={})
    axlsx_binding = Kernel.binding
    locals.each do |key, value|
      axlsx_binding.local_variable_set key, value
    end
    # define a workbook useful when testing partial in isolation
    axlsx_binding.local_variable_set(:wb, Axlsx::Package.new.workbook)

    # mimics an ActionView::Template class, presenting a 'source' method
    # to retrieve the content of the template
    source = Struct.new(:source).new(File.read(Rails.root.join(*template_path)))
    axlsx_binding.eval(ActionView::Template::Handlers::AxlsxBuilder.call(source))
    axlsx_binding.local_variable_get(:wb)
  end
end
```

Then I include it into my spec files: (a partial here)

```ruby
require 'spec_helper'
require 'helpers/axlsx_context'

describe 'shared/_some_partial.xlsx.axlsx' do
  include_context 'axlsx'

  it "exports " do
    #setup data used in the template 
    @message_counts = Struct.new(:count_all, :positives, :negatives, :neutrals).new(42,23,15,25)

    #render the template, passing eventual locals
    wb = render_template({header_style: nil})
    expect(wb.worksheets.length).to eq(1)
    sheet = wb.worksheets[0]
  end
end
```

There it is the best I could do to make testing as easy as possible

**Comment by straydogstudio** [comment]
@sly7-7 Thanks for the code. Too busy to even read it, but I will. I'll respond soon.

**Comment by sly7-7** [comment]
@straydogstudio You're welcome, and don't worry, the code will always stay here :smile:

**Comment by jupychen** [comment]
Wow, I think you are too busy to respond it.

**Comment by straydogstudio** [comment]
Ha ha. Yeah. It's a nice bit of code though. Which is why I don't close the issue. I need to link to it in the README.

**Comment by sly7-7** [comment]
I'm currently trying to update to Rails 5, and this code does not work anymore. Maybe you can help me...
Previously, including the helper module in the specs or in the shared context worked well, but now, when in the axlsx template I call `render` to render a partial, the method of the modules are no more available. Though this continues to work well when running the Rails app.
I can't find how I could make these methods accessible again.

**Comment by straydogstudio** [comment]
@sly7-7 I'll take a look when I can. I have very little time these days, but I will get to it eventually. I'm glad you at least have a work around.

**Comment by sly7-7** [comment]
@straydogstudio yup, no problem. I think something change with rails 5, and this is not directly related to your gem. The modules where previously included in the `ActionView::CompiledTemplates` instances, even during the tests, but it seems like that's not the case anymore.
This is not a crucial thing btw, so when you eventually have the time to look, let me now if I can help.

**Comment by sly7-7** [comment]
@straydogstudio I'm currently doing some housekeeping and wanted to close this. Do you want me to just make a PR, putting (this piece of code)[https://github.com/straydogstudio/axlsx_rails/issues/31#issuecomment-107851799] in the README ?
Can I close this one anyway ?

**Comment by straydogstudio** [comment]
Closed! No worries. I'd be happy to merge it if you create a PR.

**Comment by sly7-7** [comment]
Will try to remember do it on monday :smile:
