### ISSUE TITLE
How to setup output excel file with group-by columns

### ISSUE THREAD

**Issue by jamieabc** [straydogstudio/axlsx_rails#36]
Hi, after using this gem to generate excel file, I found columns in generated worksheet cannot execute operations of 'group-by' (group columns into a group so that I can expand/shrink group of columns). Is there any way to avoid this situation?

**Comment by straydogstudio** [comment]
First, axlsx_rails is a thin wrapper around axlsx. Are you able to reproduce the problem (or not) with a simple script? (Make sure it isn't your version of axlsx that has an issue.)

Second, if that doesn't work, post your controller/template code and Gemfile.lock here.

**Comment by jamieabc** [comment]
I think it could be problem of axles, cause I tried this [example](https://github.com/randym/axlsx/blob/master/examples/example.rb), the output excel file cannot group columns. So it might not be problem of axlsx_rails.
