### ISSUE TITLE
 Invalid byte sequence in UTF-8 when generating spreadsheet

### ISSUE THREAD

**Issue by samuelshih** [straydogstudio/axlsx_rails#37]
@straydogstudio 
In my rails app, I'm trying to attach a generated xlsx file (basic) in a Sidekiq delayed mail. I'm getting the `error: WARN: invalid byte sequence in UTF-8` every time I run the sending jobs.

mailer.rb
```
xlsx = (render_to_string handlers: [:axlsx], formats: [:xlsx],
    template: "report", layout: false)
attachments["#{subject}.xlsx"] = { mime_type: Mime::XLSX, content: xlsx }
```

report.xlsx.axlsx
```
wb.add_worksheet(:name => "Custom Report") do |sheet|
   sheet.add_row ["wrap", "me", "Up in Red"], :style => red_border
   sheet.add_row [1, 2, 3], :style => blue_border
end
```

Gem version 0.3.0, Rails 4.1.7, Ruby 2.2.0

Gemfile
```
...
gem 'sidekiq'
gem 'sidetiq'
gem 'rack-timeout'
gem 'axlsx_rails'
```

If I comment out the xlsx block, email sends fine.
Thanks for your help in advance :smile:

**Comment by samuelshih** [comment]
@straydogstudio any updates?

**Comment by straydogstudio** [comment]
Sorry @samuelshih I haven't been able to get to it. One way you could help is to create a simple Rails repo in Github that demonstrates the issue. Then I won't have to set that up, and it will make sure I have the setup you do (with the entire Gemfile.) Would you be willing to do that?

**Comment by samuelshih** [comment]
@straydogstudio I figured it out!!
```
xlsx = (render_to_string handlers: [:axlsx], formats: [:xlsx],
    template: "report", layout: false)
attachments["#{subject}.xlsx"] = { mime_type: Mime::XLSX, content: xlsx }
```

```
  mail(
      to: params[:email],
      from: "money@trycaviar.com",
      subject: subject,
      template_path: 'mailer',
      template_name: "report"
    )
```

The template in the xlsx block `report` can't have the same name as the html template. So I had to rename it to

```
xlsx = (render_to_string handlers: [:axlsx], formats: [:xlsx],
    template: "xls_report", layout: false)
attachments["#{subject}.xlsx"] = { mime_type: Mime::XLSX, content: xlsx }
```

**Comment by samuelshih** [comment]
@straydogstudio I figured it out!!
```
xlsx = (render_to_string handlers: [:axlsx], formats: [:xlsx],
    template: "report", layout: false)
attachments["#{subject}.xlsx"] = { mime_type: Mime::XLSX, content: xlsx }
```

```
  mail(
      to: test@email.com,
      from: "emaill@test.com",
      subject: subject,
      template_path: 'mailer',
      template_name: "report"
    )
```

The template in the xlsx block `report` can't have the same name as the html template. So I had to rename it to

```
xlsx = (render_to_string handlers: [:axlsx], formats: [:xlsx],
    template: "xls_report", layout: false)
attachments["#{subject}.xlsx"] = { mime_type: Mime::XLSX, content: xlsx }
```
It was always breaking on `mail( ....)`, so I was thinking it might be getting the template names confused even when I wasn't attaching the xlsx file, so there it is :smile:

**Comment by straydogstudio** [comment]
Fantastic! That's great. I think I may know what that means then, but I'll have to check on that. Nice to have a simple solution!

**Comment by straydogstudio** [comment]
I'm going to leave this open as a reminder to look into this.

**Comment by kikihakiem** [comment]
Hey @straydogstudio , I also faced with the same problem. It looks like rails are trying to surround the xlsx file with layouts:
![image](https://cloud.githubusercontent.com/assets/4023108/11456398/09cd8ac0-96ba-11e5-9f78-5e37ef2efb67.png)
To fix this problem I have to either rename the axlsx template or by passing `render layout: false`, so my controller action looks like this:
```
respond_to do |format|
      format.html
      format.csv { send_data as_csv }
      format.xls { render layout: false } # avoid surrounding xml with layout
      format.xlsx { render layout: false }
    end
```
I prefer the later one.

**Comment by straydogstudio** [comment]
@kikihakiem Thanks for the update. The format.xls really shouldn't come into play, as I don't register anything under that MIME type. But that is interesting. 

What Rails / Axlsx / axlsx_rails versions do you have?

**Comment by kikihakiem** [comment]
Rails 4.2.4, axlsx 2.0.1, axlsx_rails 0.4.0
Ignore that `format.xls`, it does neither relate to your gem or this issue. However I got the same issue when generating xls file using stdlib, so I think it's rails issue.

**Comment by straydogstudio** [comment]
I have *not* been able to reproduce this bug. But, based on the experience of others (here and in other issues) the latest release of axlsx_rails (0.5.0) explicitly sets layout to false. Advising others to set the layout to false appears to fix these issues. I am cautiously optimistic. Please try 0.5.0 and comment on this issue (or open another) if the failure happens again.

**Comment by nachokb** [comment]
ref #29 (dupe)
