### ISSUE TITLE
Creating a document with large number of records

### ISSUE THREAD

**Issue by bighoax** [straydogstudio/axlsx_rails#39]
Hello is it possible to do some kind of batching? I have about 100k records, and my server crashes as soon as I try to export all of them. My template looks like this :

```
excel(xlsx_package) do |excel|
  excel.worksheet("Report") do |worksheet|
    worksheet.header "Reports", formatted_time(@timestamp) do
      worksheet.row
      worksheet.row style: excel.styles(:heading_centered), default_column_width: 18, height: 35 do |row|
        row.cell " A1"
        row.cell " A2"
        row.cell " A3"
        row.cell " Author"
        row.cell " Previous Value"
        row.cell " Current Value"
        row.cell " Timestamp"
      end
    end

    worksheet.body() do
      @reports.each do |bv|
        bv.formatted_changeset.each do |key, value|
          worksheet.row do |row|
            row.cell bv.deal.attribute_1
            row.cell bv.deal.attribute_2
            row.cell bv.deal.attribute_3
            row.cell bv.user.name
            row.cell value.first
            row.cell value.last
            row.cell bv.created_at.strftime('%b %e, %Y %I:%M %p %Z')
          end
        end
      end
    end
  end
end
```

I'm using rails 4, was thinking the use the `find_each` and basically write to a temp file in batches, and then serve the file from the filesystem to a user. Is this a possibility? Otherwise how do you solve the large record set issue?

**Comment by straydogstudio** [comment]
@bighoax : I assume @reports is the record collection. I would definitely try the find_each first. Loading 100k ruby objects into memory is probably your issue. You could also generate a spreadsheet with 100k rows of random data without loading records. If that works then Axlsx isn't the issue.

**Comment by bighoax** [comment]
@straydogstudio yes it was not this library issue but the records loaded N+1 relation data, thanks
