### ISSUE TITLE
axlsx file is not display anything which is string in 'Number software' of mac

### ISSUE THREAD

**Issue by jigneshkhokhani** [straydogstudio/axlsx_rails#43]
I generate XLSX file and it's generate proper and open in windows MS Excel and its open perfect.

But when i open in 'Number software' of mac then it not  display string value.

I try to assign data type like this : -

sheet.add_row [col_1, col_2, col_3, col_4, col_5], :types => [:string, :string, :string, :integer, :string]

but it display blank for sting and number type display properly.

Even if i define or not define any type then also nothing display in mac "Number software".

**Comment by straydogstudio** [comment]
@jigneshkhokhani This looks like it is an Axlsx issue or Numbers issue. I'm afraid I do not have a solution for you, as I am not a Numbers user. 

I suggest creating this issue on the axlsx gem site, and posting a question on stackoverflow.com.

**Comment by jigneshkhokhani** [comment]
Thanks for response. I will ask.

**Comment by straydogstudio** [comment]
@jigneshkhokhani If you can demonstrate that it is indeed an axlsx_rails issue (and it doesn't happen with Axlsx only) be sure to open this up again.

**Comment by divyang9389** [comment]
@jigneshkhokhani  your question is right I face same issue. Axlsx give support.
just try with 
p = xlsx_package.workbook
p.workbook.add_worksheet(:name => "Basic Worksheet") do |sheet|
  sheet.add_row ["First Column", "Second", "Third"]
  sheet.add_row [1, 2, 3]
end
p.use_shared_strings = true


its work for me so I hope also work for you.

**Comment by oesgalha** [comment]
Setting `use_shared_strings = true` in the workbook fixed the problem to me too. :)

Thanks, @divyang9389  :+1:
