### ISSUE TITLE
ActionController::UnknownFormat if no explicit action is specified in the controller

### ISSUE THREAD

**Issue by jmuheim** [straydogstudio/axlsx_rails#44]
Whilte http://localhost:3005/de/projects/1/boilerplate_copies.xlsx results in Rails sending me some attachment, http://localhost:3005/de/projects/1/findings.xlsx results in `ActionController::UnknownFormat`.

I have the following two files, which both are empty:

- `app/views/findings/index.xlsx.axlsx`
- `app/views/boilerplate_copies/index.xlsx.axlsx`

Then I found out that the `BoilerplateCopiesController` has an explicit `#index` action, while `FindingsController` doesn't.

According to my knowledge, it's not Rails-style to require the controller to have an action explicitly defined - it's enough to have a view for it. So I guess this is a bug - or at least an annoyance that should be improved.

**Comment by straydogstudio** [comment]
Thanks @jmuheim. I'll get to it when I can. 

Does the empty attachment that downloads open?

Off the top of my head, what you may find is that it results from the default format types that come with the default action. The request follows a different path through the controller and view when there is no action or explicit render statement. Have you tried it with any other type of extension, like a pdf?

Would you tell me what version of Rails, axlsx, axlsx_rails, and rubyzip are specified in your Gemfile.lock file?

**Comment by straydogstudio** [comment]
@jmuheim Incidentally, this is apparently fixed in Rails 5 without any changes. It is in the resolver code. I'm will still try to do what I can with Rails 4.

**Comment by straydogstudio** [comment]
@jmuheim I've finally dedicated some extensive time trying to reproduce this. I thought I had, but it turned out to be a faulty test. At this point I have no problem getting to a template without an action. I will close this for now. If you ever wish to, reopen this and provide a simple rails app that duplicates the issue.
