### ISSUE TITLE
Unable to run rails server with gem:  "already initialized constant APP_PATH"

### ISSUE THREAD

**Issue by rdgco** [straydogstudio/axlsx_rails#45]
I added the axlsx_rails gem and installed in my project. If I run the rails server, I get the following error:

warning: already initialized constant APP_PATH
~/project/bin/rails:6: warning: previous definition of APP_PATH was here

I tried this with both rails 4.2.4 and 4.2.0. Here are the gem versions with using 4.2.0: 

 * actionmailer (4.2.0)
  * actionpack (4.2.0)
  * actionview (4.2.0)
  * activejob (4.2.0)
  * activemodel (4.2.0)
  * activerecord (4.2.0)
  * activesupport (4.2.0)
  * addressable (2.3.8)
  * american_date (1.1.0)
  * arel (6.0.3)
  * autoparse (0.3.3)
  * autoprefixer-rails (6.0.2)
  * axlsx (1.3.6)
  * axlsx_rails (0.1.5)
  * bcrypt (3.1.10)
  * binding_of_caller (0.7.2)
  * bootstrap-sass (3.3.5.1)
  * bourbon (4.2.4)
  * builder (3.2.2)
  * bundler (1.10.6)
  * byebug (6.0.2)
  * capybara (2.5.0)
  * childprocess (0.5.6)
  * coffee-rails (4.1.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * crack (0.4.2)
  * database_cleaner (1.5.0)
  * debug_inspector (0.0.2)
  * devise (3.5.2)
  * diff-lcs (1.2.5)
  * erubis (2.7.0)
  * execjs (2.6.0)
  * extlib (0.9.16)
  * factory_girl (4.5.0)
  * factory_girl_rails (4.5.0)
  * faraday (0.9.1)
  * ffi (1.9.10)
  * globalid (0.3.6)
  * google-api-client (0.8.6)
  * googleauth (0.4.2)
  * htmlentities (4.3.4)
  * i18n (0.7.0)
  * jasny-bootstrap-rails (3.1.3)
  * jbuilder (2.3.1)
  * jquery-rails (4.0.5)
  * json (1.8.3)
  * jwt (1.5.1)
  * launchy (2.4.3)
  * little-plugger (1.1.4)
  * logging (2.0.0)
  * loofah (2.0.3)
  * mail (2.6.3)
  * memoist (0.12.0)
  * mime-types (2.6.2)
  * mini_portile (0.6.2)
  * minitest (5.8.2)
  * mono_logger (1.1.0)
  * multi_json (1.11.2)
  * multipart-post (2.0.0)
  * nokogiri (1.6.6.2)
  * orm_adapter (0.5.0)
  * pg (0.18.3)
  * rack (1.6.4)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (4.2.0)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.2)
  * rails_apps_testing (0.3.12)
  * railties (4.2.0)
  * rake (10.4.2)
  * rdiscount (2.1.8)
  * rdoc (4.2.0)
  * redis (3.2.1)
  * redis-namespace (1.5.2)
  * responders (2.1.0)
  * resque (1.25.2)
  * resque-scheduler (4.0.0)
  * retriable (1.4.1)
  * rspec-core (3.3.2)
  * rspec-expectations (3.3.1)
  * rspec-mocks (3.3.2)
  * rspec-rails (3.3.0)
  * rspec-support (3.3.0)
  * rubyzip (1.1.7)
  * rufus-scheduler (3.1.4)
  * safe_yaml (1.0.4)
  * sass (3.4.18)
  * sass-rails (5.0.4)
  * sdoc (0.4.1)
  * selenium-webdriver (2.47.1)
  * signet (0.6.1)
  * sinatra (1.4.6)
  * singleton-rails (0.0.2.1 95d4972)
  * slim (3.0.6)
  * slim-rails (3.0.1)
  * spring (1.3.6)
  * sprockets (3.4.0)
  * sprockets-rails (2.3.3)
  * temple (0.7.6)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.1)
  * timecop (0.8.0)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
  * vcr (2.9.3)
  * vegas (0.1.11)
  * warden (1.2.3)
  * web-console (2.2.1)
  * webmock (1.21.0)
  * websocket (1.2.2)
  * will_paginate (3.0.7)
  * xpath (2.0.0)

**Comment by rdgco** [comment]
Ok, shortly after posting this I read the nice README again, and discovered my problem. After setting the following gem versions and running bundle update for those gems in my gemfile, I'm able to run the server:
gem 'rubyzip', '= 1.0.0'
gem 'axlsx', '= 2.0.1'
gem 'axlsx_rails'

**Comment by straydogstudio** [comment]
@rdgco Thanks for the feedback. Next time I get to work on the gem I'm hoping to hammer out the different gem version compatibilities. Not sure if I can do that as an automated test but I will try. At the very least I would like an error in the log or during bundle update if this is the case. I'm reluctant to lock the gem down to axlsx 2.0.x, but that may have to happen.
