### ISSUE TITLE
No error. Not rendering anything.

### ISSUE THREAD

**Issue by pvin** [straydogstudio/axlsx_rails#46]
followed this
http://stackoverflow.com/questions/24053901/rails-export-records-to-downloadable-excel-file-using-axlsx-gem

log:
Rendered elements/generate_xlsx.xlsx.axlsx (13.6ms)
Rendered text template (0.0ms)
Sent data MeetingDetailsReport.xlsx (0.6ms)
Completed 200 OK in 28ms (Views: 27.6ms | ActiveRecord: 0.7ms)

No error. Not rendering anything. any help here?

**Comment by straydogstudio** [comment]
@pvin A few things I can think of:

* Isolate the xlsx code in a script, funning it with rails runner, and see if you can generate the xlsx file and save it to a temp directory. This will let you know if it is Axlsx code or axlsx_rails code. 
* Post your template/controller code here, and I'll take a look. Sometimes a misnamed variable leaves you with no content.

**Comment by pvin** [comment]
@straydogstudio Thanks for quick response. 

Controller

def generate_xlsx
    @elements = Element.all
    respond_to do |format|
      format.xlsx { render xlsx: 'generate_xlsx', filename: "MeetingDetailsReport.xlsx"}
    end
  end

View

wb = xlsx_package.workbook
wb.add_worksheet(name: "Payments") do |sheet|
    sheet.add_row ["ID", "Notes","Amount($)","Deposit Date"]
    @elements.each do |element|
        sheet.add_row [element.name]
    end
end

**Comment by straydogstudio** [comment]
@pvin I'm not seeing anything obvious. If you use Chrome developer tools on the page, does the Network tab say anything about what is returned? What _exact _URL are you calling to view the page?

**Comment by straydogstudio** [comment]
@pvin If you still need something, and haven't gotten around this, try adding `layout: false` to the render statement.
