### ISSUE TITLE
:b does not work (Numbers)

### ISSUE THREAD

**Issue by lwnhp** [straydogstudio/axlsx_rails#48]
the style 'bold' boolean (:b) does not work in Numbers? In Excel it works ok. Don't know if this a axlsx_rails issue or axlsx_styler issue (which I'm also using)? thnx.

**Comment by straydogstudio** [comment]
@lwnhp That would either be axlsx_styler or axlsx. axlsx_rails is a thin wrapper around axlsx. I assume you are using a rich text cell? I've not tried to do much with Numbers. I believe axlsx tries to follow the open spec for xlsx, but I have no experience in twiddling with Mac characters for styling or formatting.

A quick search finds:
https://github.com/randym/axlsx/blob/master/examples/example.rb#L843-L860

Which I expect you have already found.

**Comment by straydogstudio** [comment]
I'm going to close this. Reopen if needed.
