### ISSUE TITLE
How to start new page?

### ISSUE THREAD

**Issue by henriquesacramento** [straydogstudio/axlsx_rails#49]
I did not found documentation to explain how to i can jump to new page during generator.

**Comment by straydogstudio** [comment]
What do you mean by jump to a new page? Show me a bit of code, or give me a better description. If you mean rendering a different template, you do it in the normal rails way, calling `render xlsx: 'nameoftemplate'` in the controller.

**Comment by straydogstudio** [comment]
If you mean adding a different worksheet, look at the documentation for Axlsx. axlsx_rails is just a wrapper around that gem, which is what does all the work of creating your spreadsheet. Here is the examples page:

https://github.com/randym/axlsx/blob/master/examples/example.rb

**Comment by henriquesacramento** [comment]
Ok thanks!
