### ISSUE TITLE
How to added width to nested columns?

### ISSUE THREAD

**Issue by henriquesacramento** [straydogstudio/axlsx_rails#51]
Can i add same width to nested columns?

**Comment by straydogstudio** [comment]
@henriquesacramento that's a new one for me. I do not know how to manage nested columns with axlsx. Have you tried asking on stackoverflow.com? What documentation have you found for nested columns?

**Comment by henriquesacramento** [comment]
@straydogstudio Maybe i have used a wrong description. I need create a table based in a quantity of columns, but don't know the exact quantity of rows.

**Comment by straydogstudio** [comment]
If you are needing to set the width of the columns or rows, see here:
https://github.com/randym/axlsx/blob/master/examples/example.rb#L241-L264

As for rows, you don't need to know how many you have. Not normally. Just loop through your data and add a row for each.
