### ISSUE TITLE
Issue with Dropdown values using Axlsx gem

### ISSUE THREAD

**Issue by sravani9** [straydogstudio/axlsx_rails#52]
I'm trying to populate a list of values in the dropdown of excel using axlsx gem in rails. It seems like all the values in the dropdown are being displayed in lowercase.

```
 wb = xlsx_package.workbook  
 wb.add_worksheet(name: "sample_data") do |sheet|

  sheet.add_data_validation("A2:A1000", {
    :type => :list,
    :formula1 => "Red Orange NavyBlue",
    :showDropDown => false,
    :showErrorMessage => true,
    :errorTitle => '',
    :error => 'Please use the dropdown selector to choose the value',
    :errorStyle => :stop,
    :showInputMessage => true,
    :prompt => 'Choose the value from the dropdown'}) 
  end
```

In the dropdown, the values are appearing as red,orange,navyblue.

Is there a way, by which I can display the data as it is without the conversion to lowercase?(Red,Orange,NavyBlue)

Please help me out to solve this issue.

**Comment by straydogstudio** [comment]
Have you tried entering the data in a range of cells and referring to them: `formula1 => "sheetname!A1:A20"`?

**Comment by sravani9** [comment]
Thanks for the response!
Yes,I have tried that.But the problems that I am facing are,

1) Firstly I am unable to hide the sheet using state:  :hidden( also tried using  state:  :very_hidden)
2) And the dropdown values keep on decreasing. For ex., if there are total of 10 values that need to be displayed in the dropdown list, the first cell dropdown contains 10, next cell 9, and so on it goes on decreasing.

**Comment by straydogstudio** [comment]
Try absolute references on the row numbers. "sheetname!A$1:A$20"

**Comment by sravani9** [comment]
Awesome! It worked..
Thanks a lot for the quick responses!

Still a small issue.Once I select values from dropdown and save the file, and when I reopen the file I see that the dropdown is no more available for the remaining cells which were not selected earlier.(The dropdown remains only for the previously selected cells)

Also I'm able to hide the column but unable to hide the sheet as a whole( tried using state: :hidden)

**Comment by straydogstudio** [comment]
I expect that means the program is changing the file upon save. I know Axlsx tries to conform to the open office standard, but individual programs have some grey areas. Have you tried opening it and saving it in a different program, say Open Office?

I've not ever tried to hide a sheet. I expect that may have to do with standards as well. Again, is it hidden when you open it in a different program? These kind of things are annoying.

**Comment by sravani9** [comment]
Yes, the problem seems to be with Libre Office and it works fine with Open Office.

Thanks a lot for the solutions provided. It helped me :)

**Comment by straydogstudio** [comment]
Glad to hear it worked!
