### ISSUE TITLE
Cannot start the server with gem axlsx or axlsx_rails

### ISSUE THREAD

**Issue by lpbryant** [straydogstudio/axlsx_rails#54]
I cannot start the server after adding the gem "acts as xlsx" to my gemfile.

I have read other posts on this problem but still haven't got a clue what is going on. Most seem to have resolved the problem by removing the gem from the gemfile. If I remove the gem, I can start the server but I need it to do what I want to do. Also, I get the same message if I use the gem "axlsx" or "axlsx_rails", so I believe that something that is required in this gem is creating this issue.

The error message is

"bin/rails:6: warning: already initialized constant APP_PATH /home/ubuntu/workspace/horsestud_app/bin/rails:6: warning: previous definition of APP_PATH was here
Error: Command '-b' not recognized"
 if I run "rake -D --trace
I get:
LoadError: cannot load such file -- zip/zip
/usr/local/rvm/gems/ruby-2.2.1/gems/axlsx-1.3.6/lib/axlsx.rb:26:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/axlsx-1.3.6/lib/axlsx.rb:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/axlsx_rails-0.1.5/lib/axlsx_rails.rb:1:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/axlsx_rails-0.1.5/lib/axlsx_rails.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:134:in `require'
/home/ubuntu/workspace/horsestud_app/config/application.rb:10:in `<top (required)>'
/home/ubuntu/workspace/horsestud_app/Rakefile:4:in `require'
/home/ubuntu/workspace/horsestud_app/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.2.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

I have tried it with the gem 'rubyzip', :require => 'zip/zip' in the gemfile, but this makes not difference.  I have also tried to put the require axlsx, require axlsx_rails in various rails.rb, application.rb   in my workspace for the application but this does not achieve anything.

I really will appreciate any help I can be given to resolve this.

Thanking you in advance,

**Comment by straydogstudio** [comment]
You've ended up with axlsx 1.3.6 because you added acts_as_xlsx first. You'll want at least this in your Gemfile:

```
gem 'rubyzip', '= 1.0.0'
gem 'axlsx', '= 2.0.1'
gem 'axlsx_rails'
```

You could also use the github repo for axlsx. Another zip option is `gem 'zip-zip'`. 

The acts_as_xlsx gem is not compatible with Rails 4 or above (if I remember correctly.) You'll want to use my version of the acts_ax_xlsx repo: https://github.com/straydogstudio/acts_as_xlsx.

Let me know how it goes.

**Comment by straydogstudio** [comment]
Note, for acts_as_xlsx you can also use the branch that was created off of my version:

```
gem 'acts_as_xlsx', git: "https://github.com/randym/acts_as_xlsx.git", branch: "straydogstudio-master"
```

It's the eventual new acts_as_xlsx, but work on it has stalled.

**Comment by lpbryant** [comment]
You are truly a "gem"!   I have been struggling with this for over a week doing various things.   As you would guess, I am entirely new at axlsx, axlsx_rails and acts_as_xlsx.      Do you have a recommended starting place?   In one of your articles it says you assume that we know "I18n" and I noted that an example had algorithms in the en.yml file and although I know what these are used for, I am not sure of the relevance with regards to axlsx.   I really need to start at the beginning.   Please advise.

**Comment by straydogstudio** [comment]
Hey that's ok! There's a lot of stuff going on here. And you're welcome.

It sounds like you are referring to an article written by @randym, the author of axlsx. I don't remember writing anything about I18n. In general it is pretty straightforward. Are you doing multiple translations? If not, I would set it aside and not worry about it until you know you need it. 

I would start as simple as possible. Create basic spreadsheets using `.xlsx.axlsx` templates. Add charts if you need them. In most cases that will be all you need. Wait until you have a problem, then solve it. Don't make any ahead of time!

**Comment by straydogstudio** [comment]
Also, tests will help. They can help you define what you need to do ahead of time and keep you from doing too much. Look at the tests for axlsx for examples. 

If you don't know how to make tests, start giving yourself time each week to learn it. It can feel really big, but it doesn't have to be.

**Comment by straydogstudio** [comment]
By the way, if you ever use Roo to read xlsx files, you'll need to change your Gemfile. See the top of the Readme.

**Comment by lpbryant** [comment]
I will.  Thanks very much!
