### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by miks** [straydogstudio/axlsx_rails#56]
As Rails 5.0 is out now, can we get compatibility release in rubygems, please?

**Comment by straydogstudio** [comment]
I will soon. It's there but for some unfinished tests and fixes. Have you been using the repo? If so, have you seen any issues?

**Comment by miks** [comment]
No, I'm not used because in my case it's dependancy in another gem.

**Comment by straydogstudio** [comment]
Which gem?

**Comment by miks** [comment]
Nothing famous - https://github.com/cubesystems/releaf

**Comment by pastullo** [comment]
@straydogstudio i am about to use this gem in a Rails 5.0 project over the weekend, will let you know if any problem arise.

**Comment by straydogstudio** [comment]
Thanks. My test suite ran with no errors or deprecations using the repo. I am totally buried. But hope to get this out in the next few days.

**Comment by straydogstudio** [comment]
Version 0.5.0 with Rails 5 support and testing is published.
