### ISSUE TITLE
zipruby compatibility

### ISSUE THREAD

**Issue by mikeLspohn** [straydogstudio/axlsx_rails#60]
Is there anyway to make this gem work with zipruby? I'm using this gem in a different project and love it, but I'm trying to integrate it into a large existing Rails app, but zipruby is used so I get conflict errors when trying to install rubyzip with zipruby. I'm using Spreadsheet gem in the app now and I'm really missing axlsx-rails.

Does anyone know of any workarounds to this?

**Comment by mikeLspohn** [comment]
Looking more into this, it seems like this is probably an issue for the axlsx gem itself.

**Comment by straydogstudio** [comment]
Yes it would have to do with Axlsx, not axlsx_rails. I'm not familiar with the locations in Axlsx that rubyzip is used. But, it might be possible to monkey patch Axlsx for zipruby. It depends on how rubyzip is used.
