### ISSUE TITLE
Missing Template error in production

### ISSUE THREAD

**Issue by pulkit21** [straydogstudio/axlsx_rails#61]
```
I, [2016-09-08T17:25:44.073936 #41694]  INFO -- : Started GET "/admin/tablets_list" for 127.0.0.1 at 2016-09-08 17:25:44 +0530
I, [2016-09-08T17:25:44.107349 #41694]  INFO -- : Processing by Admin::CabinetsController#tablets_list as HTML
I, [2016-09-08T17:25:44.199807 #41694]  INFO -- :   Rendered admin/cabinets/tablets_list.html.erb within layouts/admin/application (63.1ms)
I, [2016-09-08T17:25:44.202837 #41694]  INFO -- :   Rendered shared/_flash_notifier.html.erb (0.6ms)
I, [2016-09-08T17:25:44.203983 #41694]  INFO -- : Completed 200 OK in 97ms (Views: 64.0ms | ActiveRecord: 10.0ms)
I, [2016-09-08T17:25:47.090020 #41694]  INFO -- : Started GET "/download_excel.xlsx" for 127.0.0.1 at 2016-09-08 17:25:47 +0530
I, [2016-09-08T17:25:47.091346 #41694]  INFO -- : Processing by Admin::CabinetsController#download_excel as XLSX
I, [2016-09-08T17:25:47.099323 #41694]  INFO -- : Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.2ms)
F, [2016-09-08T17:25:47.100854 #41694] FATAL -- :
ActionView::MissingTemplate (Missing template admin/cabinets/download_excel, admin/base/download_excel, application/download_excel with {:locale=>[:en], :formats=>[:xlsx], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/Users/pulkit/dev/dev-scotta-smartcabinets/app/views"
  * "/Users/pulkit/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/app/views"
):
  app/controllers/admin/cabinets_controller.rb:12:in `block (2 levels) in download_excel'
  app/controllers/admin/cabinets_controller.rb:11:in `download_excel'


```

Controller action

```
def download_excel
  @cabinets = Cabinet.all
  respond_to do |format|
    format.xlsx {render xlsx: 'download_excel',filename: "smart_cab.xlsx"}
  end
end
```

In development its working fine without any error but in production it's giving me the `Template missing` error, please help.

**Comment by straydogstudio** [comment]
@pulkit21 If you could set up a repo with the applicable parts, that would be great. It may be an interaction with another gem. Are you using an admin gem? If you can't do a repo, please create a gist with more code (including the Gemfile) so I can reproduce this. I can see what the problem is, I need to recreate it.

**Comment by straydogstudio** [comment]
What versions of Rails, Axlsx, axlsx_rails, and rubyzip are you using?

**Comment by pulkit21** [comment]
@straydogstudio 
Rails- 4.2.1
Axlsx- 2.0.1
axlsx_rails- 0.1.5
rubyzip- 1.0.0

**Comment by pulkit21** [comment]
This is a Gemfile gist
https://gist.github.com/pulkit21/1dd8b3424c1dd1742b6bf56f6c5881a2

**Comment by straydogstudio** [comment]
I don't think it will help, but have you tried Axlsx '2.1.0.pre' and rubyzip 1.1.0?

**Comment by straydogstudio** [comment]
@pulkit21 I think I have it. You've got axlsx and axlsx_rails inside development/test in your Gemfile. Move that outside and I expect it would work. 

If you look in your error, there is no axlsx handler listed. That would fit.

**Comment by pulkit21** [comment]
Silly me I didn't notice that the gems are under development/test. Thanks a lot @straydogstudio for pointing out my mistake.

**Comment by straydogstudio** [comment]
You're welcome.

**Comment by nitin-cis** [comment]
I am having the same issue of `missing template` in production environment and my gem are also out of development/test environment in Gemfile

gem 'rubyzip', '>= 1.2.1'
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
gem 'axlsx_rails'

can anyone help me on this.

**Comment by straydogstudio** [comment]
@nitin-cis Do you have axlsx_rails 0.5.2 in your Gemfile.lock? I would add your comment to [issue 100](https://github.com/straydogstudio/axlsx_rails/issues/100). So far I haven't been able to reproduce the error, but I will keep trying. If you are willing to post your Gemfile.lock to a gist for me to look at that might help.
