### ISSUE TITLE
Microsoft Excel Removed Feature: Table from /xl/tables/table1.xml part (Table)

### ISSUE THREAD

**Issue by haykwork** [straydogstudio/axlsx_rails#62]
This is how xlsx file appears in LibreOffice (Ubuntu 14.04)
![2138d161e1](https://cloud.githubusercontent.com/assets/15094395/18911536/b1dffee6-858e-11e6-81d2-4a8601f0db67.jpg)

But when I tried to open same file on windows or mac with Microsoft Excel sortable headers were removed .

**Comment by straydogstudio** [comment]
@haykwork Was there a solution or was it an error?
