### ISSUE TITLE
0.5.0 generated xlsx file corrupted on windows/mac os x

### ISSUE THREAD

**Issue by samuel-christian** [straydogstudio/axlsx_rails#64]
Using:
rubyzip (1.1.7)
axlsx (2.1.0.pre)
axlsx_rails (0.5.0)
rails 4.2.5

The file can be opened on Ubuntu and it's just fine (I use 14.04). But it cannot be opened on either windows or mac.
I'm only able to provide screenshot from windows.

Snippet code in my controller to export to excel:
```
respond_to do |format|
  format.html
  format.xlsx {
    response.headers['Content-Disposition'] = 'attachment; filename="' + @filename + '.xlsx"'
  }
end
```

Snippet code my `xlsx.axlsx` file:
```
require 'axlsx'

wb = xlsx_package.workbook
wb.add_worksheet do |sheet|
  sheet.add_row ["#{@table_title}"]
  sheet.merge_cells("A1:D1")
  sheet.add_row ["Num", "Date", "Articles", "Clicks"]
  index = 1
  @article_count.reverse_each do |key, article|
    sheet.add_row [index, key, article[0], article[1]]
    index += 1
  end
  sheet.column_widths 5, nil, 10, nil
end
```

Is there any additional configuration that I forget to support cross platform?
Please help.

![error export to excel](https://cloud.githubusercontent.com/assets/11038716/21800111/b5f8d4c8-d74e-11e6-939f-c9a652be6ec5.JPG)

**Comment by straydogstudio** [comment]
Would you try passing a name to add_worksheet to see what happens? 

`wb.add_worksheet(name: "Articles")`

**Comment by straydogstudio** [comment]
Also, downgrade to 0.4.0 and see if that changes things.

**Comment by samuel-christian** [comment]
ok, will do
I will post the result after I try it

thanks for replying, by the way

**Comment by straydogstudio** [comment]
Did you happen to try a named sheet with 0.5.0? If you get a chance, I would appreciate it. I've had difficulty reproducing this error.

**Comment by straydogstudio** [comment]
Thanks for getting back to me by the way.

**Comment by fabioaraujo121** [comment]
I've tried what @samuel-christian did but with no success.
I got no log errors and anything like that.
What am I missing?

Gemfile
```ruby
gem 'rubyzip', '~> 1.1.0' 
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails', '0.4.0'
```

And here's my template:
```ruby
require 'axlsx'
# encoding: UTF-8

wb = xlsx_package.workbook

wb.add_worksheet(name: "Atividades") do |sheet|
  sheet.add_row ["Carga Horária Cumprida", "Carga Horária Validada"]
  sheet.add_row [@done_workload, @validated_workload]
  sheet.add_row
  # this is the head row of your spreadsheet
  sheet.add_row ["STATUS", "JUSTIFICATIVA", "UNIDADE", "TAREFA", "DURAÇÃO(min)", "COMEÇO", "TÉRMINO", "COMEÇOU", "DISTÂNCIA(começo)", "TERMINOU", "DISTÂNCIA(término)", "RELATÓRIO"]
  
  # each user is a row on your spreadsheet
  @activities.each do |a|
  	if a.done?
  		sheet.add_row [Web::V1::LayoutHelper::Activity::status(a.status), a.justification_text, a.unity.name, a.task.title, 
      ((a.checkpoints.last.at - a.checkpoints.first.at) / 60).to_i, I18n.l(a.beginning_at), I18n.l(a.end_at), I18n.l(a.checkpoints.first.at), (a.checkpoints.first.distant ? "DISTANTE" : "PRÓXIMO"), I18n.l(a.checkpoints.last.at), (a.checkpoints.last.distant ? "DISTANTE" : "PRÓXIMO"), Web::V1::SpreadsheetHelper::activity_report(a.report)]
  	elsif a.to_do?
  		sheet.add_row [Web::V1::LayoutHelper::Activity::status(a.status), "", a.unity.name, a.task.title, "", I18n.l(a.beginning_at), I18n.l(a.end_at), "", "", ""]
  	elsif a.canceled?
  		sheet.add_row [Web::V1::LayoutHelper::Activity::status(a.status), a.justification_text, a.unity.name, a.task.title, "", I18n.l(a.beginning_at), I18n.l(a.end_at), "", "", ""]
  	elsif a.lost?
  		sheet.add_row [Web::V1::LayoutHelper::Activity::status(a.status), a.justification_text, a.unity.name, a.task.title, "", I18n.l(a.beginning_at), I18n.l(a.end_at), "", "", ""]
  	end
  end
end
```

**Comment by straydogstudio** [comment]
@fabioaraujo121 It is really hard to know what might cause this. It is most likely an issue between Axlsx, what you are putting in the spreadsheet (possibly special characters), and the version of office suite you are using. Here are some ideas to help track down the problem:

* Make sure it isn't axlsx_rails: Create a plain ruby script that uses Axlsx to create your sheet. See if it helps.
* Make sure it isn't your data: Vary your data, or make it plain vanilla, or remove sections of your sheet, until you find what is causing the problem. It could involve special characters. 
* Open it with other office suites to see if there are any issues. 

All axlsx gems have moved into a community organization. If it appears to be an Axlsx issue consider adding an issue to http://github.com/caxlsx/caxlsx. You will probably have to create a repo of an environment that reproduces your problem for it to be solved.
