### ISSUE TITLE
Issue due to rubyzip dependency

### ISSUE THREAD

**Issue by marcelomita29** [straydogstudio/axlsx_rails#66]
After installing the gem I had the following error:
`/lib/active_support/dependencies.rb:247:in 'require': cannot load such file -- zip/zip (LoadError)`

I think that rubyzip needs to be required as `require 'zip'` instead of `require 'zip/zip'`

**Comment by straydogstudio** [comment]
@marcelomita29 Thanks for the note. And glad you got it working. 

axlsx_rails only depends on actionpack and axlsx. Axlsx leaves some ambiguity in the rubyzip dependency, and rubyzip had breaking changes at 1.0, so issues happen. In practice it is necessary to declare rubyzip in your gemfile also:

https://github.com/straydogstudio/axlsx_rails#installation
