### ISSUE TITLE
`self.instance_variable_set(:@_lookup_context, nil)` needed in mailer

### ISSUE THREAD

**Issue by jasonknebel** [straydogstudio/axlsx_rails#69]
> After you have rendered the template to string, and before you call the mailer, execute self.instance_variable_set(:@_lookup_context, nil). If you must do this, please open an issue

I had to add this code to get the attachment working. I also had to take out the encoding to get it to work also.

```ruby
def test_email(model_id)
  @obj = Model.find(model_id)
  xlsx = render_to_string(template: 'models/model_export')
  attachments["model.xlsx"] = { mime_type: Mime[:xlsx], content: xlsx }
  self.instance_variable_set(:@_lookup_context, nil)

  mail(to: 'test@example.com', subject: 'test')
end
```

Ruby: 2.4.0
Rails: 5.0.1
axlsx (2.0.1)
axlsx_rails (0.5.0)

Please let me know what additional information you require.

**Comment by straydogstudio** [comment]
Thanks @jasonknebel.

**Comment by jasonknebel** [comment]
I was able to get it working without needed that line. I think the default layout I was using for the mailer was causing the conflict. This code works now:
```ruby
report = render_to_string(layout: false, template: 'models/model_export')
attachments[@model.report_filename] = { mime_type: Mime[:xlsx], content: report }
```

**Comment by straydogstudio** [comment]
Excellent. I have seen the layout cause issues.

**Comment by straydogstudio** [comment]
I've added it to the readme.
