### ISSUE TITLE
path to generated file to use in javascript app

### ISSUE THREAD

**Issue by jaredgalanis** [straydogstudio/axlsx_rails#70]
Similar to issue #33 I am attempting to send an ajax request from a JS (ember) app to the rails server to generate a file with axlsx_rails. I would like to respond to request with the url of the generated file so that I can feed it to an iframe and have the file download client side. However, I can't seem to figure out where the path of the generated file is. Any help would be most appreciated!

**Comment by straydogstudio** [comment]
By default axlsx_rails doesn't generate a file. It goes straight out to the response. So you'll want to have the iframe source go to whatever controller / action has your result, passing the xlsx extension. At least, that is the normal way to do it. If you are scheduling a job, you will either have to put it somewhere inside `public`, or save its location and spool out the file with another controller action (that has the benefit of letting you control who has access.) In this latter case, Rails will have to explicitly use render to string or the like to generate a file from the template (the readme has instructions.) Or, if you don't care about a template, then use ruby and axlsx directly and save the file somewhere. There are lots of ways to do it. It depends on what you need. Let me know if you need anything more specific.

**Comment by jaredgalanis** [comment]
Thanks @straydogstudio. No job scheduling in this case. I am sending data from the JS app to the rails controller / action that the axlsx template will use in building the file. If I provide the iframe source the controller / action, will it just send a request there without the data I'm intending to pass along?

**Comment by straydogstudio** [comment]
I would pass the parameters to the src of the iframe as a get request.

**Comment by jaredgalanis** [comment]
so I'm doing this in my controller action: 
```    @filename = "#{Rails.root}/public/export_requisition_statistics_report.xlsx"
    File.open(@filename, 'w') do |f|
      f.write render_to_string(handlers: [:axlsx], formats: [:xlsx], template: '/api/v1/reports/export_requisition_statistics_report.xlsx.axlsx')
    end

    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"export_requisition_statistics_report.xlsx\""
      }
    end```

This seems to save the file to the public folder of my rails app. Then I am using an iframe on the JS side to trigger the download.
```var iframe = $("<iframe/>").attr({
                                src: '/export_requisition_statistics_report.xlsx',
                                style: "visibility:hidden;display:none"
                            }).appendTo('#exportButton');```
Does this sound reasonable?

**Comment by straydogstudio** [comment]
That should be fine.

**Comment by jaredgalanis** [comment]
Thanks!
