### ISSUE TITLE
Line numbers in stack trace don't line up with source

### ISSUE THREAD

**Issue by BenoitHiller** [straydogstudio/axlsx_rails#71]
If the code in my axlsx template raises an error the line numbers in the resulting stack trace are wrong.

Similarly the source shown in the development error screen will not line up and pry will not be able to display the correct line when debugging.

So if you make a file containing only `raise 'error'` it will tell you the error is on line 9.

The reason for this is that in `lib/axlsx_rails/template_handler.rb` you are adding newlines onto each line you append. However the convention in rails template helpers appears to be that you don't append newlines into the generated source(you just do as you have done and separate each "line" into a separate string and concat them all).

Rails expects the template source lines to match the generated source lines even if their actual contents are different. See https://github.com/rails/rails/blob/master/actionview/lib/action_view/template/handlers/builder.rb

**Comment by straydogstudio** [comment]
Thanks @BenoitHiller. I'll try to make a release soon to update this, since it is a simple fix.

**Comment by straydogstudio** [comment]
@BenoitHiller 0.5.1 released with this fix.
