### ISSUE TITLE
Turbolinks can mess things up

### ISSUE THREAD

**Issue by JohnSmall** [straydogstudio/axlsx_rails#72]
The latest version of Turbolinks will display the generated Excel file in the <body> of the <html>

Which is obviously not what's required. It took me hours to work it out but the link to your action to generate and download the Excel file needs to be

 `link_to 'download Excel',my_excel_path,data:{turbolinks: false}
`
So the documentation needs to be updated to reflect the new Turbolinks behaviour.

**Comment by straydogstudio** [comment]
Thanks for sharing this. I'll add a section on Turbolinks to the README. 

Did it change with a newer version of Turbolinks, or did it work in the past?

**Comment by straydogstudio** [comment]
Turbolinks section added to troubleshooting in the Readme.
