### ISSUE TITLE
Error undefined method `each_with_index'

### ISSUE THREAD

**Issue by Selmor** [straydogstudio/axlsx_rails#73]
Using the code from the tutorial, the server responds with a 500: 
ActionView::Template::Error (undefined method `each_with_index' for #<Axlsx::SimpleTypedList:0xb0c4f2e>

MyCode:
wb = xlsx_package.workbook
wb.add_worksheet(name: "Findings") do |sheet|
  @findings.each do |finding|
    sheet.add_row [finding.id]
  end
end

Best Regards

**Comment by straydogstudio** [comment]
@Selmor Which tutorial are you looking at?

**Comment by Selmor** [comment]
https://www.sitepoint.com/generate-excel-spreadsheets-rails-axlsx-gem/

**Comment by straydogstudio** [comment]
Can you post a more complete stack trace?

**Comment by Selmor** [comment]
Sorry, but there are no more information in the log file:

Completed 500 Internal Server Error in 161ms (ActiveRecord: 2.0ms)
ActionView::Template::Error (undefined method `each_with_index' for #<Axlsx::SimpleTypedList:0x736674f>
Did you mean?  each_index):

**Comment by straydogstudio** [comment]
Hm. That's a bit odd. Can you do something dead simple like this and not get an error:

```ruby
  sheet.add_row ['hello', 'there']
```

and remove your @findings loop?

**Comment by straydogstudio** [comment]
I'm assuming you've found a solution. Reopen if you need more help.

**Comment by straydogstudio** [comment]
I'm guessing this was jRuby. See issue https://github.com/straydogstudio/axlsx_rails/issues/83
