### ISSUE TITLE
is possible one chart, multiple style series?

### ISSUE THREAD

**Issue by susemi99** [straydogstudio/axlsx_rails#76]
![screenshot](https://cloud.githubusercontent.com/assets/1233318/24950027/90314b90-1faa-11e7-8a17-e8228efaecfe.png)
like this?

**Comment by straydogstudio** [comment]
@susemi99 Unfortunately I've done very little with Axlsx charts. I do not have an answer for you. I suggest trying http://stackoverflow.com.
