### ISSUE TITLE
Hi, I have a problem  invalid byte sequence in UTF-8:

### ISSUE THREAD

**Issue by arigatodon** [straydogstudio/axlsx_rails#80]
Hello my problem happens when you respond 
        respond_to do |format|
            format.xlsx {render xlsx: xlsx,filename: "ler.xlsx"}
        end
I was seeing other solutions but I did not understand how to use it with the respond

**Comment by straydogstudio** [comment]
@arigatodon There could be several reasons, including the data itself. What is your template at this point?

**Comment by arigatodon** [comment]
this is the content template http://bit.ly/2ro18Qb

**Comment by straydogstudio** [comment]
@arigatodon Did you get it working? Sorry for the delay. I would first try removing both loops and returning just your headers (make sure there isn't a problem with your data.) Then I would strip out the styles to make sure they aren't the issue.

**Comment by straydogstudio** [comment]
Incidentally your respond_to statement looks fine.
