### ISSUE TITLE
Rendered xlsx file contains only class instance reference

### ISSUE THREAD

**Issue by constantm** [straydogstudio/axlsx_rails#81]
I can't figure out what I'm doing wrong. The file that gets generated consists of only the following:

`#<Axlsx::Worksheet:0x007fb607872bb0>`

I've removed all my own code and I'm using very basic example code with no luck.

Controller:
```
# controllers/dashboards_controller.rb
def export
    respond_to do |format|
      format.xlsx do
        render xlsx: 'export', filename: "#{@survey_def.name}"
      end
    end
end
```

View:
```
# views/dashboards/export.xlsx.axlsx
wb = xlsx_package.workbook
wb.add_worksheet(name: "Products") do |sheet|
  sheet.add_row ['test1', 'test2']
end
```

I'm using axlsx_rails 0.5.1 with axlsx 2.0.1 and Rails 4.2.8

**Comment by straydogstudio** [comment]
Take the render statement out of the format block and drop the format block. Or, replace the render with:

`response.headers["Content-Disposition"] = 'attachment; filename="' + @survey_def.name + '"'`

In other words, it is trying to render twice, because the format block is also calling render.

**Comment by constantm** [comment]
Thanks for the super speedy reply! I've tried replacing `render` with your suggested code, but I now receive a new error:

```
undefined method `empty?' for #<Axlsx::Worksheet:0x007fa912b89198>
```

It seems that this has to do with Rack and Etag digest generation for downloads. The fix for this appears to be setting the `Last-Modified` header, or to set the `Cache-Control` header to `no-cache`. However, doing this results in Chrome saying "Failed - Network error" when attempting to download the file and a new error:

```
Read error: #<NoMethodError: undefined method `bytesize' for #<Axlsx::Worksheet:0x007fa90ee5a380>
```

**Comment by straydogstudio** [comment]
Do you still have the respond_to block? Try this:

```
def export
    render xlsx: 'export', filename: "#{@survey_def.name}"
end
```

**Comment by constantm** [comment]
If I comment out the `respond_to` block and just use `render` like you suggested I'm back with the downloaded file containing a reference to the object instance:

`#<Axlsx::Worksheet:0x007fb607872bb0>`

I had a look at the log, and it seems that the template render is followed by another render:

```
Rendered dashboards/export.xlsx.axlsx (1.5ms)
Rendered text template (0.0ms)
```

This might be part of what's causing the issue.

**Comment by constantm** [comment]
I got it working by removing `axlsx_rails`, putting the view code in the controller and using `send_data`:

```
p = Axlsx::Package.new
wb = p.workbook
p.use_shared_strings = true
wb.add_worksheet(name: "Products") do |sheet|
  sheet.add_row ['test1', 'test2']
end
send_data p.to_stream.read, type: "application/xlsx", filename: "filename.xlsx" and return
```

**Comment by straydogstudio** [comment]
Glad you got it working. If you're ever inclined to try it again sometimes passing layout: false often fixes things. It's an odd rails bug I've never been able to isolate. If you're willing I'd like to see your gemfile contents. Thanks

**Comment by constantm** [comment]
So weird. I've used `axlsx_rails` in the past with zero issues. Gemfile looks like this:

```
source 'https://rubygems.org'
ruby '2.3.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.0'

# Use sqlite3 as the database for Active Record
gem 'pg'

# charts
gem 'chartkick'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'local_time'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'puma'

# authentication
gem 'devise'

# authorisation
gem 'cancan'

# Seed files
gem 'seed_dump'

# Icons in app
gem 'font-awesome-rails'

# Validation
gem 'judge'

# XLS exports
gem 'rubyzip', '~> 1.1.0'
gem 'axlsx', '2.1.0.pre'

# Attachments
gem 'paperclip', '~> 5.1.0'
gem 'aws-sdk'#, '< 2.0'
gem 'trim_blobs' # Trim log blobs from paperclip_database uploads

# Nested Forms
gem 'cocoon'

gem 'rails_autolink'

# Facebook
gem 'koala', '~> 1.10.0rc'

gem 'delayed_job_active_record'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development do
  gem 'sqlite3'
  gem 'letter_opener'
end

group :production do
  gem "rack-timeout"
  gem 'rails_12factor'
end

gem 'rename'

# Use debugger
gem 'pry', group: [:development, :test]

```

Disclaimer: I didn't set up this Gemfile. :)

**Comment by straydogstudio** [comment]
Ha. Gemfiles take on a life of their own! I've had a few like that. :)

Incidentally, you could also try alxlsx_rails 0.5.1, where I tried to address the layout issue. It's tough to do so when you have no failing test case though. 

I've had zero issues too, until Rails 4. They did some kind of caching with the lookup context and it introduced problems with this gem. Axlsx_rails is quite simple. It really shouldn't be an issue. For instance, some people had the layout get included when generating a mailer attachment when the mail template had the same name as the email action. ??!

Thanks for the Gemfile. I'll close this. Reopen it if you ever decide to try again.

**Comment by straydogstudio** [comment]
@constantm By chance do you have anything other than a single default layout?

**Comment by constantm** [comment]
@straydogstudio Yup, I have about 4.

**Comment by straydogstudio** [comment]
@constantm I realize you've moved on, but if you ever have time and are willing, would you try adding this to your affected controller, and add axlsx_rails again? I still have no broken test to fix.

It shouldn't affect anything else (famous last words), but I've not tested it outside my testing suite. 

```ruby
class DashboardsController < ApplicationController
    layout Proc.new { |c| return (c.request.format.symbol == :xlsx ? false : :default) }

    ...
end
```

No pressure. Thanks for your help so far.
