### ISSUE TITLE
Deprecation Warning: Mime::XLSX to Mime[:xlsx]

### ISSUE THREAD

**Issue by Hugosirq** [straydogstudio/axlsx_rails#82]
When building xlsx, I am receiving this message:

`DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change 'Mime::XLSX' to 'Mime[:xlsx]'`

Should the gem be updated to this new syntax?

I am using rails 5.0.1, and ruby 2.2.5

**Comment by straydogstudio** [comment]
Thanks @Hugosirq. I'll get to that in the next release. Do you happen to know when it will be removed?

**Comment by straydogstudio** [comment]
@Hugosirq I fixed it everywhere but in one spot. Didn't get picked up in my testing I guess. And, on further research, the "new" syntax has been around forever. So I don't need to detect the rails version. I should look more closely next time. Thanks again for the heads up.

**Comment by straydogstudio** [comment]
Original Rails pull request: https://github.com/rails/rails/pull/21869

**Comment by straydogstudio** [comment]
5.1 has removed access through constants.

**Comment by straydogstudio** [comment]
@Hugosirq Which axlsx_rails version are you using?

**Comment by Hugosirq** [comment]
Hmmm, looking at my gem file list, it appears:
axlsx (2.1.0.pre, 2.0.1)
axlsx_rails (0.5.1, 0.3.0)

Now, looking at my .lock, for some reason bundler installed(or it is using) 0.3.0 .
ASAP I will try forcing with 0.5.0 version and see if it works.

**Comment by straydogstudio** [comment]
That would explain the deprecation. I'm glad to get rid of the conditionals in the code, however. And I'm now setting up automated testing for 5.1.
