### ISSUE TITLE
Save as PDF?

### ISSUE THREAD

**Issue by cwilliamsnh** [straydogstudio/axlsx_rails#84]
Is there a way to save a spreadsheet/workbook as a PDF?

**Comment by straydogstudio** [comment]
Not within Axlsx. You'll either want to create a table in a pdf with something like Prawn, or save a file and convert it to pdf using some utility, which there should be something. 

It's older (I used it within Rails 3 apps) but you can look at [MetaReports](https://github.com/straydogstudio/meta_reports). That was my attempt to create a meta data structure for common table reports. Once I put the data in the structure, I could convert it to html, pdf, or xlsx. You could make your own structure and do the same. The default templates might save you time if you go that route.
