### ISSUE TITLE
Uninitialized constant Mime::XLSX

### ISSUE THREAD

**Issue by Erowlin** [straydogstudio/axlsx_rails#85]
Hello, 

I'm currently experiencing issues with the gem, I've this error: `uninitialized constant Mime::XLSX`

![screen shot 2017-08-03 at 15 22 11](https://user-images.githubusercontent.com/1775878/28923809-9cff5f66-785f-11e7-9ea1-18dd517bae0c.png)

(Please note that there is no typo ;)). 

Versions:
- Ruby 2.4.1.p111
- Rails 5.1.1
- axlsx (2.1.0.pre)
- axlsx_rails (0.1.5)
- rubyzip (~> 1.1.7)

What I did so far: 
- `spring stop`
- restart rails server
- read multiple time https://github.com/straydogstudio/axlsx_rails#troubleshooting
- added those lines in the `config/initializers/mime_types.rb`
```ruby
# Add new mime types for use in respond_to blocks:
Mime::Type.register "application/vnd.ms-excel", :xls
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", :xlsx
```

Let me know if you need any additional informations. 

Thanks!

**Comment by Erowlin** [comment]
Another message when using the `respond_to`: 


![screen shot 2017-08-03 at 16 08 17](https://user-images.githubusercontent.com/1775878/28925764-19fd378a-7866-11e7-9b56-461e475de567.png)

**Comment by straydogstudio** [comment]
You'll want to use a newer axlsx_rails than that. The current version is 0.5.1, which has had the Mime references changed for Rails 5.1. Do you know how you got 0.1.5?

**Comment by Erowlin** [comment]
Hey @straydogstudio thanks for your answer. By the meantime, I've been looking at the code, and this change fixed the issue for me: 
```ruby
# axlsx_rails-0.1.5/lib/axlsx_rails/action_controller.rb
# L23
# from
send_data render_to_string(options), :filename => download_name, :type => Mime::XLSX, :disposition => disposition
# to
send_data render_to_string(options), :filename => download_name, :type => Mime[:xlsx], :disposition => disposition
``` 

(This is probably the fix you're talking about, just posting as a reference). 

And for this gem version, it's the default that my `bundle install` downloaded. 
I installed multiple version to try to fix the issue. First, I followed instructions on the homepage: 
```
If rubyzip >= 1.2.1 is needed:

gem 'rubyzip', '>= 1.2.1'
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: '776037c0fc799bb09da8c9ea47980bd3bf296874'
gem 'axlsx_rails'
```

Then I tried to bump all versions and the rubyzip from `1.2.2` to `1.1.0` (BTW is it still true?)
and now my gemfile looks like this: 
``` 
gem 'rubyzip', '~> 1.1.0'
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails'
```

What I don't understand is that I did `gem uninstall axlsx` and `gem uninstall axlsx_rails` before doing bundle install. Do you think that's something related? Should I manually remove the entries of `axlsx*` versions in my Gemfile.lock then re run `bundle install`?

I'm currently testing to force the latest version in my Gemfile, I will post a new message to let you know about it. 

Thanks anyway!

**Comment by straydogstudio** [comment]
I'd just make your gemfile contain: `gem 'axlsx_rails', '>= 0.5.1'. But yes, that is the change required in the gem. I may change the README if that is happening so people specify the versioni.

**Comment by Erowlin** [comment]
Ok, thanks. 

It worked properly using the latest gem version. 

Can you confirm me that the `rubyzip` version has to be `~> 1.1.0` >

**Comment by straydogstudio** [comment]
That should be it for 2.1.0.pre. If you need 1.2.1 or greater you'll have to look at the install instructions for the git ref to choose. I've not dug through Axlsx issues for a while, so they may have a better release. They still haven't released 2.1.0. 

https://github.com/straydogstudio/axlsx_rails#installation

**Comment by martinstreicher** [comment]
Changing to use `gem 'axlsx_rails', '>= 0.5.1'` worked for me. 

My Gemfile:

```
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844' # MIT-License
gem 'axlsx_rails', '>= 0.5.1' # MIT-License
...
gem 'rubyzip', '>= 1.2.1' # Ruby license
```

**Comment by aniketstiwari** [comment]
Since rails 5 make use of Mime[:xlsx] 
For rails 4 Mime::XLSX
