### ISSUE TITLE
Scale must be greater than or equal to 1

### ISSUE THREAD

**Issue by arigatodon** [straydogstudio/axlsx_rails#87]
When I try to upload a generated file to a web I display this error Scale must be greater than or equal to 1

**Comment by straydogstudio** [comment]
@arigatodon That's not much information to go on. It could be almost anything. I don't know what you are opening it in, what your spreadsheet is (it could be strictly bad data), or any other part of the process. axlsx_rails is pretty simple. Can you create the spreadsheet manually in a script, save it to file, and test that?
