### ISSUE TITLE
using same styles in different .xlsx.axlsx views

### ISSUE THREAD

**Issue by kashifnaseer** [straydogstudio/axlsx_rails#88]
I've different .xlsx.axlsx views which are using almost same styles. i want to declare them at one common place and re-use them to avoid duplication of code. what is best way to do it ?

**Comment by straydogstudio** [comment]
@kashifnaseer I'm very sorry but I have totally missed this issue. Did you get this solved?

Controller instance variables should be visible in the template like normal. You should be able to use a partial to set them and use them in another template. But I have never tested this. Also, I don't know if the `locals:` method of passing variables will let them be modified in the partial and available in the parent, but that also might be worth checking:

`render :partial => 'styles', :locals => {:styles => styles}`

Reopen this if needed.

**Comment by Yaponcik** [comment]
I just use a helper 
for example 
`#AxlsxHelper.rb`

`module XlsxHelper
  def style_for_body(style)
    style.add_style(border: Axlsx::STYLE_THIN_BORDER)
  end
end`

`#export.axlsx.xlsx`

`wb = xlsx_package.workbook
 wb.styles do |style|

  body_style = style_for_body(style)

  wb.add_worksheet(name: "Users") do |sheet|
    @users.each do |user|
    sheet.add_row row, style: body_style
    end
  end
end
`
