### ISSUE TITLE
Add date format on specific column

### ISSUE THREAD

**Issue by brijeshs-atharvasystem** [straydogstudio/axlsx_rails#89]
Hi

I would like add date format on specific column. So by default values are shown based on specific date format.
How I can do that?

Thanks
Brijesh Shah

**Comment by straydogstudio** [comment]
Have you tried using a custom date format?

https://github.com/randym/axlsx/blob/master/examples/example.rb#L324-L340

https://gist.github.com/randym/3719401

**Comment by brijeshs-atharvasystem** [comment]
Thanks for reply. I checked these articles. I think these will help to apply on row / cell rather than specific column. I would like to apply date format on specific column.

**Comment by straydogstudio** [comment]
I'm not an Axlsx expert, but my understanding is all styles are applied by cell as you add each row of data. You might get better answers through the Axlsx issues page:

https://github.com/randym/axlsx/issues
