### ISSUE TITLE
Error when using asterisk

### ISSUE THREAD

**Issue by fblupi** [straydogstudio/axlsx_rails#93]
When I add a row with a string that contains an asterisk:

`sheet.add_row ["#{name}"]`, where name = `ASDF**`

I get an error in the controller

**Comment by straydogstudio** [comment]
What is the error stack trace?

**Comment by fblupi** [comment]
It just shows this image: 

<img width="695" alt="nqb1f" src="https://user-images.githubusercontent.com/6973564/33030615-0fbfce16-ce1c-11e7-9e4d-fa2b09eb4458.png">

**Comment by straydogstudio** [comment]
What about in your logs? It should show something about the error in either your production or development log.

**Comment by straydogstudio** [comment]
@fblupi I'm going to close this for now. If you have new information open the issue again.
