### ISSUE TITLE
Not showing repeated headers

### ISSUE THREAD

**Issue by JohnSmall** [straydogstudio/axlsx_rails#95]
In the examples.rb for axslx 2.0.1.pre there's an example to show how to extract one row and use that row as a repeated header when printing. It works. But..

When I try the same technique in a template it doesn't work. I've even removed all my data from the template and copied in the exact same code from examples.rb and it doesn't work.

The code for repeated headers in the axslx gem examples works. The same code used inside a axlsx template doesn't work.

Any idea what I might be doing wrong?

**Comment by straydogstudio** [comment]
what version of Axlsx and axlsx_rails is being used in your app? Can you do the headers inside a Rails script with rails runner (or in the console by manually entering the code)?

**Comment by straydogstudio** [comment]
It looks like this is an Axlsx issue. Let me know if you want to revisit it.
