### ISSUE TITLE
MIME registration on Rails 5.1.4

### ISSUE THREAD

**Issue by fernandoluizao** [straydogstudio/axlsx_rails#96]
After update to master, I'm getting the following error:

`
NoMethodError (To respond to a custom format, register it as a MIME type first: http://guides.rubyonrails.org/action_controller_overview.html#restful-downloads. If you meant to respond to a variant like :tablet or :phone, not a custom format, be sure to nest your variant response within a format response: format.html { |html| html.tablet { ... } }):
`

Seems like mime type it's not being registered:

https://github.com/straydogstudio/axlsx_rails/commit/312e9a2a10a1134722ac94190b8e1b10fc4f6864#diff-5a24ae1bf27adaa88e4ecc85163dbcc3

Any clues?

**Comment by straydogstudio** [comment]
@fernandoluizao What Axlsx version is in your lock file? Is this for a regular action?

This is the line in axlsx_rails that should be called:
https://github.com/straydogstudio/axlsx_rails/blob/master/lib/axlsx_rails/action_controller.rb#L3

What exact url are you calling?

**Comment by fernandoluizao** [comment]
@straydogstudio Before the update I was using 6fa9e59a8701, and everything was working. 

After update to 2790d03c95 I'm getting the error.

I'm calling the url like /materials.xlsx

My index action looks like this:

```
  def index
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="materials.xlsx"'
      }
    end
  end
```

**Comment by straydogstudio** [comment]
@fernandoluizao Thanks. That looks simple enough I should be able to test it.

**Comment by fernandoluizao** [comment]
@straydogstudio could you reproduce the issue? I updated to rails 5.1.5 today, tested with axlsx_rails master, same error.

Just a question, why did you change Mime::XLSX to Mime[:xlsx]? Using 6fa9e59 I see no deprecation warning from rails...

**Comment by straydogstudio** [comment]
@fernandoluizao I haven't been able to get to this. I expect to next week, though perhaps before; I'll be on a business trip for my job. It should be noted that there should be no differences between the repo and 0.5.1. You might get some deprecation warnings, but it should not cause you any issues (as far as I know of course.) 

I changed to Mime[:xlsx] because Mime::XLSX was supposed to be removed. It was in the deprecations for 5.1. Evidently there is something else going on, or they changed their mind.

**Comment by josephpage** [comment]
I've got the same issue with rails 5.1.5, ruby 2.5, axlsx 545d773, and axlsx_rails 2790d03.
Works with axlsx_rails 6fa9e59.

**Comment by straydogstudio** [comment]
Thanks @josephpage. I'll track it down in the next week.

**Comment by straydogstudio** [comment]
@fernandoluizao @josephpage The latest commit c8acfcd should fix this issue. Let me know if it works for you.

**Comment by fernandoluizao** [comment]
Works! Thanks a lot!
